version: '3.8'


services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
#    networks:
#      - trace-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - node.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
#    networks:
#      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.1
    container_name: logstash
    environment:
      - LOGSTASH_JAVA_OPTS=-Xmx512m -Xms512m
    ports:
      - "9600:9600"
      - "4560:4560"  # Expose the TCP port for Logstash
    volumes:
      - ./pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    command: logstash -f /Users/subhamjoshi/Documents/DevOps/spring-jenkins/config/logstash.conf
#    networks:
#      - elastic
    depends_on:
      - elasticsearch
#    networks:
#      - trace-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
#    networks:
#      - elastic


#networks:
#  elastic:
#    driver: bridge

volumes:
  elasticsearch_data:
    driver: local

#  docker rmi $(docker images -q) --force
#  docker-compose build
#  docker-compose up

# /opt/homebrew/etc/logstash/logstash.conf