version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - trace-network

networks:
  trace-network:
    driver: bridge

#  docker rmi $(docker images -q) --force
#  docker-compose build
#  docker-compose up